//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Agents.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Agents.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A required property on AgentHost is missing: {0}.
        /// </summary>
        internal static string AgentHostMissingProperty {
            get {
                return ResourceManager.GetString("AgentHostMissingProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A required property on Agent &apos;{0}&apos; settings is missing: {1}.
        /// </summary>
        internal static string AgentMissingProperty {
            get {
                return ResourceManager.GetString("AgentMissingProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent &apos;{0}&apos; not found..
        /// </summary>
        internal static string AgentNotFound {
            get {
                return ResourceManager.GetString("AgentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token Provider &apos;{0}&apos; for Agent &apos;{1}&apos; not found..
        /// </summary>
        internal static string AgentTokenProviderNotFound {
            get {
                return ResourceManager.GetString("AgentTokenProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SendToAgent &apos;{0}&apos; failed.
        /// </summary>
        internal static string SendToAgentFailed {
            get {
                return ResourceManager.GetString("SendToAgentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SendToAgent &apos;{0}&apos; failed: Unauthorized.
        /// </summary>
        internal static string SendToAgentUnauthorized {
            get {
                return ResourceManager.GetString("SendToAgentUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SendToAgent &apos;{0} failed with an unsucessful response &apos;{1}&apos;..
        /// </summary>
        internal static string SendToAgentUnsuccessful {
            get {
                return ResourceManager.GetString("SendToAgentUnsuccessful", resourceCulture);
            }
        }
    }
}
