// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

using Microsoft.Agents.Builder.Errors;
using Microsoft.Agents.Builder.State;
using Microsoft.Agents.Core;
using Microsoft.Agents.Core.Errors;
using Microsoft.Agents.Core.Models;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace Microsoft.Agents.Builder
{
    /// <summary>
    /// This class enables sending chunked text in a series of "intermediate" messages, on an interval.  This
    /// gives the UX of a streamed message. When complete, a final message (ActivityType.Message) is sent with 
    /// the full message and optional Attachments.
    /// 
    /// The expected sequence of calls is:
    /// 
    /// `QueueInformativeUpdateAsync()`, `QueueTextChunk()`, `QueueTextChunk()`, ..., `EndStreamAsync()`.
    ///
    ///  Once `EndStreamAsync()` is called, the stream is considered ended and no further updates can be sent.
    /// </summary>
    /// <remarks>
    /// Only Teams and WebChat support streaming messages.  However, channels that do not support
    /// streaming messages will only receive the final message when <see cref="EndStreamAsync"/> is called.
    /// </remarks>
    /// <remarks>
    /// This class support throttling via the <see cref="Interval"/> property.  Teams and Azure Channels require
    /// some throttling since services like OpenAI produce streams that exceed allowed Channel message limits.
    /// Teams defaults to 1000ms per intermediate message, and WebChat 500ms.  Reducing the Interval could result
    /// in message delivery failures.
    /// </remarks>
    internal class StreamingResponse : IStreamingResponse
    {
        public static readonly int DefaultEndStreamTimeout = (int)TimeSpan.FromMinutes(2).TotalMilliseconds;

        private const string TeamsStreamCancelled = "ContentStreamNotAllowed";
        private const string TeamsStreamTimedOut = "Content stream finished due to exceeded streaming time.";
        // Teams failed to accept streaming messages. 
        private const string BadArgument = "BadArgument";
        private const string TeamsStreamNotAllowed = "streaming api is not enabled";
                
        private readonly TurnContext _context;
        private int _nextSequence = 1;
        private bool _ended = false;
        private Timer _timer;
        private bool _processingTimer = false; 
        private bool _messageUpdated = false;
        private bool _isTeamsChannel;
        private bool _canceled;
        private bool _userCanceled;
        private bool _streamTimedOut = false;
        private string _lastInformationalMessageSent = string.Empty;
        private DateTime? _streamStartTime;
        private TimeSpan _streamElapsedTime;
        private DateTime? _lastPassTime;
        private ChannelId _channelId;


        // Queue for outgoing activities
        private readonly List<Func<IActivity>> _queue = [];
        private readonly AutoResetEvent _queueEmpty = new(false);

        /// <summary>
        /// Set IActivity that will be (optionally) used for the final streaming message.
        /// </summary>
        public IActivity FinalMessage { get; set; }

        /// <summary>
        /// Gets the stream ID of the current response.
        /// Assigned after the initial update is sent.
        /// </summary>
        public string StreamId { get; private set; }

        /// <summary>
        /// The buffered message.
        /// </summary>
        public string Message { get; private set; } = "";

        /// <summary>
        /// Gets or sets a value indicating whether the feedback loop functionality is enabled.
        /// </summary>
        /// <remarks>This currently only works for Teams channels.</remarks>
        public bool FeedbackLoopEnabled { get; set; } = false;

        /// <summary>
        /// Gets or sets the type of feedback loop used in the system.
        /// </summary>
        /// <remarks>The default value is "default". This property influences how feedback is processed
        /// and utilized within the application. Teams also supports "custom".</remarks>
        public string FeedbackLoopType { get; set; } = "default";

        /// <summary>
        /// Sets the "Generated by AI" label in Teams.
        /// Defaults to false.
        /// </summary>
        public bool? EnableGeneratedByAILabel { get; set; } = false;

        /// <summary>
        /// The citations for the response.
        /// </summary>
        public List<ClientCitation>? Citations { get; set; } = [];

        /// <summary>
        /// The sensitivity label for the response.
        /// </summary>
        public SensitivityUsageInfo? SensitivityLabel { get; set; }

        /// <summary>
        /// Attachments to be included in the final message.  This is only used for the final message, and not for intermediate messages.
        /// </summary>
        public List<Attachment>? Attachments { get; set; } = [];

        /// <summary>
        /// The interval in milliseconds at which intermediate messages are sent.
        /// </summary>
        /// <remarks>
        /// Teams default: 1000
        /// WebChat default: 500
        /// </remarks>
        /// <exception cref="ArgumentOutOfRangeException">Thrown when set to a negative value.</exception>
        public int Interval
        {
            get => _interval;
            set
            {
                if (value < 0)
                    throw new ArgumentOutOfRangeException(nameof(value), value, "Interval must be greater than or equal to 0.");
                _interval = value;
            }
        }

        private int _interval;

        /// <inheritdoc/>
        public int EndStreamTimeout { get; set; } = DefaultEndStreamTimeout;

        /// <summary>
        /// The initial delay in milliseconds before the first intermediate message is sent.
        /// Defaults to 250. Set to a small value in tests.
        /// </summary>
        /// <exception cref="ArgumentOutOfRangeException">Thrown when set to a negative value.</exception>
        public int InitialDelay
        {
            get => _initialDelay;
            set
            {
                if (value < 0)
                    throw new ArgumentOutOfRangeException(nameof(value), value, "InitialDelay must be greater than or equal to 0.");
                _initialDelay = value;
            }
        }

        private int _initialDelay = 250;

        /// <summary>
        /// Indicate if the current channel supports intermediate messages.
        /// </summary>
        /// <remarks>
        /// Channels that don't support intermediate messages will buffer
        /// text, and send a normal final message when EndStreamAsync is called.
        /// </remarks>
        public bool IsStreamingChannel { get; private set; }

        /// <summary>
        /// Gets the number of updates sent for the stream.
        /// </summary>
        /// <returns>Number of updates sent so far.</returns>
        public int UpdatesSent() => _nextSequence - 1;


        // BizChat / teams Streaming timeout and pinging properties 

        /// <inheritdoc/>
        public string StreamingTakingTooLongMessage { get; set; } = "The response is taking longer than expected. Please wait while we continue to generate the response.";

        // Bizchat default timeout mitigation support
        private TimeSpan M365StreamingTimeout = new TimeSpan(0, 0, 1, 45); // 1 minute, 45 seconds default for M365 streaming timeout.  If the interval is greater than this, we will use this value instead.
        private static readonly TimeSpan BizChatWorkingNoticeInterval = new TimeSpan(0, 0, 0, 35); // BizChat requires an update within ~45 seconds, otherwise it will timeout.


        /// <summary>
        /// Creates a new instance of the <see cref="StreamingResponse"/> class.
        /// </summary>
        /// <param name="turnContext">Context for the current turn of conversation with the user.</param>
        public StreamingResponse(TurnContext turnContext)
        {
            AssertionHelpers.ThrowIfNull(turnContext, nameof(turnContext));

            _context = turnContext;
            SetDefaults(turnContext);
        }

        /// <inheritdoc/>
        public void AddAttachment(Attachment attachment)
        {
            AssertionHelpers.ThrowIfNull(attachment, nameof(attachment));            Attachments ??= [];
            Attachments.Add(attachment);
        }

        /// <inheritdoc/>
        public void AddCitation(Citation citation, int citationPosition)
        {
            Citations ??= [];
            Citations.Add(new ClientCitation()
            {
                Position = citationPosition,
                Appearance = new ClientCitationAppearance()
                {
                    Name = citation.Title ?? $"Document #{citationPosition}",
                    Abstract = CitationUtils.Snippet(citation.Content, 480),
                    Url = citation.Url
                }
            });
        }

        /// <inheritdoc/>
        public void AddCitations(IList<Citation> citations)
        {
            if (citations.Count > 0)
            {
                Citations ??= [];

                int currPos = Citations.Count;

                foreach (Citation citation in citations)
                {
                    Citations.Add(new ClientCitation()
                    {
                        Position = currPos + 1,
                        Appearance = new ClientCitationAppearance()
                        {
                            Name = citation.Title ?? $"Document #{currPos + 1}",
                            Abstract = CitationUtils.Snippet(citation.Content, 480),
                            Url = citation.Url
                        }
                    });
                    currPos++;
                }
            }
        }

        /// <inheritdoc/>
        public void AddCitation(ClientCitation citation)
        {
            Citations ??= [];
            Citations.Add(citation);
        }

        /// <inheritdoc/>
        public void AddCitations(IList<ClientCitation> citations)
        {
            if (citations.Count > 0)
            {
                Citations ??= [];
                Citations.AddRange(citations);
            }
        }

        /// <inheritdoc/>
        public async Task QueueInformativeUpdateAsync(string text, CancellationToken cancellationToken = default)
        {
            if (_channelId == Channels.M365Copilot)
            {
                // BizChat has a behavior that will cause the stream to visually error if there have been no updates every 45 seconds, this is a compensation to deal with sending a notice every based on the bizChat inactivity alert timer. 
                _lastInformationalMessageSent = text;
                _lastPassTime = DateTime.UtcNow;
            }

            if (!IsStreamingChannel)
            {
                return;
            }

            Func<IActivity> queueFunc;
            lock (this)
            {
                if (_ended)
                {
                    throw Core.Errors.ExceptionHelper.GenerateException<InvalidOperationException>(ErrorHelper.StreamingResponseEnded, null);
                }

                queueFunc = () =>
                {
                    return new Activity
                    {
                        Type = ActivityTypes.Typing,
                        Text = text,
                        Entities = [new StreamInfo()
                            {
                                StreamType = StreamTypes.Informative,
                                StreamSequence = _nextSequence++,
                            }]
                    };
                };

                if (IsStreamStarted())
                {
                    QueueActivity(queueFunc);
                    return;
                }
            }

            // if we got this far, the stream has been started so just send directly and start.
            await SendActivityAsync(queueFunc(), cancellationToken).ConfigureAwait(false);
            StartStream();
        }

        /// <inheritdoc/>
        public void QueueTextChunk(string text)
        {
            if (string.IsNullOrEmpty(text) || _canceled)
            {
                return;
            }

            lock (this)
            {
                // Setup the stream start here if this is the first event. 
                _streamStartTime ??= DateTime.UtcNow;

                if (_ended)
                {
                    throw Core.Errors.ExceptionHelper.GenerateException<InvalidOperationException>(ErrorHelper.StreamingResponseEnded, null);
                }

                // buffer all chunks
                Message += text;

                // If there are citations, modify the content so that the sources are numbers instead of [doc1], [doc2], etc.
                Message = CitationUtils.FormatCitationsResponse(Message);

                _messageUpdated = true;

                // Start stream if needed.  The InitialDelay allows for a quicker stream (better UX) if Informative hadn't been sent
                // and we're just now starting the stream.  It uses Interval after the first stream message.
                StartStream(InitialDelay);
            }
        }

        /// <inheritdoc/>
        public async Task<StreamingResponseResult> EndStreamAsync(CancellationToken cancellationToken = default)
        {
            if (!IsStreamingChannel)
            {
                lock (this)
                {
                    if (_ended)
                    {
                        return StreamingResponseResult.AlreadyEnded;
                    }

                    _ended = true;
                }

                // Timer isn't running for non-streaming channels.  Just send the Message buffer as a message.
                if (UpdatesSent() > 0 || FinalMessage != null || !string.IsNullOrWhiteSpace(Message))
                {
                    if (_streamTimedOut)
                    {
                        await UpdateActivityAsync(CreateFinalMessage(), cancellationToken).ConfigureAwait(false);
                    }
                    else
                    {
                        await _context.SendActivityAsync(CreateFinalMessage(), cancellationToken).ConfigureAwait(false);
                    }
                }

                return StreamingResponseResult.Success;
            }
            else
            {
                lock (this)
                {
                    if (_ended)
                    {
                        return StreamingResponseResult.AlreadyEnded;
                    }

                    _ended = true;

                    if (_canceled)
                    {
                        return _userCanceled ? StreamingResponseResult.UserCancelled : StreamingResponseResult.Error;
                    }

                    if (!IsStreamStarted())
                    {
                        return StreamingResponseResult.NotStarted;
                    }
                }

                StreamingResponseResult result = StreamingResponseResult.Success;

                // Wait for queue items to be sent per Interval
                try
                {
                    if (!_queueEmpty.WaitOne(EndStreamTimeout))
                    {
                        result = StreamingResponseResult.Timeout;
                    }

                    if (_canceled)
                    {
                        return _userCanceled ? StreamingResponseResult.UserCancelled : StreamingResponseResult.Error;
                    }
                }
                catch (AbandonedMutexException)
                {
                    StopStream();
                }

                if (UpdatesSent() > 0 || FinalMessage != null)
                {
                    if (_streamTimedOut)
                    {
                        await UpdateActivityAsync(CreateFinalMessage(), cancellationToken).ConfigureAwait(false);
                    }
                    else
                    {
                        await SendActivityAsync(CreateFinalMessage(), cancellationToken).ConfigureAwait(false);
                    }
                }

                return result;
            }
        }

        /// <inheritdoc/>
        public async Task<bool> SendStreamTimedOutNotification(string message, CancellationToken cancellationToken = default)
        {
            if (_ended)
            {
                return false;
            }
            await SendActivityAsync(CreateStreamStoppedMessage(message), cancellationToken).ConfigureAwait(false);
            IsStreamingChannel = false; // Disabled Streaming for this channel / Switch to Async Mode.
            StopStream(); // stop the stream timers
            return true;
        }

        private IActivity CreateFinalMessage()
        {
            var activity = FinalMessage ?? new Activity();

            activity.Type = ActivityTypes.Message;
            activity.Entities ??= [];
            if (FinalMessage == null)
            {
                activity.Text = !string.IsNullOrEmpty(Message) ? Message : "No text was streamed";   // Teams won't allow Activity.Text changes or empty text
            }

            // make sure the supplied Activity doesn't have a streamInfo already.
            var existingStreamInfos = activity.Entities.Where(e => string.Equals(EntityTypes.StreamInfo, e.Type, StringComparison.OrdinalIgnoreCase)).ToList();
            if (existingStreamInfos.Count != 0)
            {
                foreach (var existing in existingStreamInfos)
                {
                    activity.Entities.Remove(existing);
                }
            }

            if (IsStreamingChannel)
            {
                // Only append this if the channel supports streaming.
                activity.Entities.Add(new StreamInfo() { StreamType = StreamTypes.Final, StreamResult = (string.IsNullOrEmpty(Message) ? StreamResults.Error : StreamResults.Success) });
            }

            if (_streamTimedOut && !string.IsNullOrEmpty(StreamId))
            {
                activity.Id = StreamId;
            }

            if (FeedbackLoopEnabled && _isTeamsChannel)
            {
                activity.ChannelData = ObjectPath.Merge(activity.ChannelData, new
                {
                    feedbackLoop = new
                    {
                        type = FeedbackLoopType ?? "default"
                    }
                });
            }

            // Add in Generated by AI
            List<ClientCitation>? currCitations = CitationUtils.GetUsedCitations(Message, Citations);
            if ((bool)EnableGeneratedByAILabel || currCitations != null)
            {
                AIEntity entity = new()
                {
                    Citation = currCitations,
                    UsageInfo = SensitivityLabel
                };

                if (EnableGeneratedByAILabel == true)
                {
                    entity.AdditionalType.Add(AIEntity.AdditionalTypeAIGeneratedContent);
                }
                activity.Entities.Add(entity);
            }

            // Add Attachments if there are any
            if (Attachments != null && Attachments.Count > 0)
            {
                if (activity.Attachments == null)
                {
                    activity.Attachments = Attachments;
                }
                else if (!ReferenceEquals(activity.Attachments, Attachments))
                {
                    foreach (var attachment in Attachments)

                    {
                        activity.Attachments.Add(attachment);
                    }
                }
            }
            return activity;
        }

        /// <summary>
        /// Used as part of stopping a stream due to timeout while streaming content continues in non-stream mode.
        /// </summary>
        /// <param name="messageText"></param>
        /// <returns></returns>
        private Activity CreateStreamStoppedMessage(string messageText)
        {
            var activity = new Activity();
            activity.Type = ActivityTypes.Message;
            activity.Entities ??= [];
            activity.Text = !string.IsNullOrEmpty(messageText) ? messageText : "No text was streamed";   // Teams won't allow Activity.Text changes or empty text

            if (IsStreamingChannel)
            {
                // Only append this if the channel supports streaming.
                activity.Entities.Add(new StreamInfo() { StreamType = StreamTypes.Final, StreamResult = (string.IsNullOrEmpty(Message) ? StreamResults.Error : StreamResults.Success) });
            }

            return activity;
        }

        /// <summary>
        /// Used as part of stopping a stream due to timeout while streaming content continues in non-stream mode.
        /// </summary>
        /// <param name="messageText"></param>
        /// <param name="addStreamFinal">if true, finalizes the stream properly.</param>
        /// <returns></returns>
        private Activity CreateStreamTimedOutMessage(bool addStreamFinal = false)
        {
            var activity = new Activity();
            activity.Type = ActivityTypes.Message;
            activity.Entities ??= [];

            bool _ShouldShowWorkingMessage = true;
            if (_ShouldShowWorkingMessage)
            {
                activity.Text = !string.IsNullOrEmpty(Message) ? ($"{Message} {Environment.NewLine}{Environment.NewLine} {StreamingTakingTooLongMessage} {Environment.NewLine}") : StreamingTakingTooLongMessage;
            }
            else
            {
                activity.Text = !string.IsNullOrEmpty(Message) ? Message : StreamingTakingTooLongMessage;   // Teams won't allow Activity.Text changes or empty text
            }


            if (_streamTimedOut && !string.IsNullOrEmpty(StreamId))
            {
                activity.Id = StreamId;
            }

            if (IsStreamingChannel)
            {
                if (addStreamFinal)
                {
                    // Only append this if the channel supports streaming.
                    activity.Entities.Add(new StreamInfo()
                    {
                        // StreamSequence = _nextSequence++,
                        StreamType = StreamTypes.Final,
                        StreamId = StreamId,
                        StreamResult = (string.IsNullOrEmpty(Message) ? StreamResults.Error : StreamResults.Success)
                    });
                    activity.Id = StreamId;
                }
                else
                {
                    if (_channelId == Channels.M365Copilot)
                    {
                        // Only append this if the channel supports streaming.
                        activity.Type = ActivityTypes.Typing;
                        var sequence = _nextSequence++;
                        activity.Entities.Add(new StreamInfo()
                        {
                            StreamType = StreamTypes.Streaming,
                            StreamSequence = sequence,
                        });
                    }
                }
            }

            return activity;
        }


        /// <Inheritdoc/>
        public async Task ResetAsync(CancellationToken cancellationToken = default)
        {
            if (IsStreamStarted())
            {
                await EndStreamAsync(cancellationToken).ConfigureAwait(false);
            }

            lock (this)
            {
                StopStream();
                _ended = false;
                _queue.Clear();
                FinalMessage = null;
                _nextSequence = 1;
                StreamId = null;
                _canceled = false;
                _userCanceled = false;
                Message = "";
                Citations = [];
                Attachments = [];
                SensitivityLabel = null;
                EnableGeneratedByAILabel = false;
                _streamTimedOut = false;
                _lastInformationalMessageSent = string.Empty;
                _streamStartTime = null;
                _streamElapsedTime = TimeSpan.Zero;
                _lastPassTime = null;
            }
        }


        /// <summary>
        /// Send current data or a holding message while the stream is still running.
        /// </summary>
        /// <param name="cancellationToken"></param>
        /// <returns></returns>
        private async Task SendStreamTimeOutCheckpoint(CancellationToken cancellationToken = default)
        {
            if (_streamTimedOut)
            {
                await UpdateActivityAsync(CreateStreamTimedOutMessage(), cancellationToken);
            }
        }


        /// <summary>
        /// Queue an activity to be sent to the client.
        /// </summary>
        /// <param name="factory"></param>
        private void QueueActivity(Func<IActivity> factory)
        {
            if (factory != null)
            {
                _queue.Add(factory);
                _queueEmpty.Reset();
            }
        }

        /// <summary>
        /// Queue the next chunk of text to be sent to the client.
        /// </summary>
        private void QueueNextChunkActivity()
        {
            if (!_messageUpdated)
            {
                return;
            }
            _messageUpdated = false;

            // Send typing activity
            var activity = new Activity
            {
                Type = ActivityTypes.Typing,
                Text = Message,
                Entities = []
            };

            // Queue a chunk of text to be sent. The Activity (including Text = Message)
            // is created here to snapshot the current state. The factory below runs later
            // to attach streaming metadata (sequence, entities) to this snapshot at send time.
            QueueActivity(() =>
            {
                var sequence = _nextSequence++;

                activity.Entities.Add(new StreamInfo()
                {
                    StreamType = StreamTypes.Streaming,
                    StreamSequence = sequence,
                });

                if (Citations != null && Citations.Count > 0)
                {
                    // If there are citations, filter out the citations unused in content.
                    List<ClientCitation>? currCitations = CitationUtils.GetUsedCitations(Message, Citations);
                    AIEntity entity = new();
                    if (currCitations != null && currCitations.Count > 0)
                    {
                        entity.Citation = currCitations;
                    }

                    activity.Entities.Add(entity);
                }

                return activity;
            });
        }

        private void SetDefaults(TurnContext turnContext)
        {
            _channelId = turnContext.Activity.ChannelId; // Need to capture the channel ID for use in the streaming logic, as the TurnContext may not be available when sending streaming activities.
            _isTeamsChannel = Channels.Msteams == turnContext.Activity.ChannelId?.Channel;

            if (string.Equals(DeliveryModes.ExpectReplies, turnContext.Activity.DeliveryMode, StringComparison.OrdinalIgnoreCase))
            {
                // No point in streaming for ExpectReplies.  Treat as non-streaming channel.
                IsStreamingChannel = false;
            }
            else if (_isTeamsChannel)
            {
                // Teams MUST use the Activity.Id returned from the first Informative message for
                // subsequent intermediate messages.  Do not set StreamId here.

                Interval = 1000;
                IsStreamingChannel = true;
            }
            else if (Channels.Webchat == turnContext.Activity.ChannelId?.Channel || Channels.Directline == turnContext.Activity.ChannelId?.Channel)
            {
                Interval = 500;
                IsStreamingChannel = true;

                // WebChat will use whatever StreamId is created.
                StreamId = Guid.NewGuid().ToString();
            }
            else if (string.Equals(DeliveryModes.Stream, turnContext.Activity.DeliveryMode, StringComparison.OrdinalIgnoreCase))
            {
                // Support streaming for DeliveryMode.Stream
                IsStreamingChannel = true;
                Interval = 100;
                StreamId = Guid.NewGuid().ToString();
            }
            else
            {
                IsStreamingChannel = false;
            }
        }

        public bool IsStreamStarted()
        {
            return _timer != null;
        }

        private void StartStream(int interval = 0)
        {
            if (_timer == null && IsStreamingChannel)
            {
                _timer = new Timer(SendIntermediateMessage, null, interval == 0 ? Interval : interval, System.Threading.Timeout.Infinite);
            }
        }

        private void StopStream()
        {
            if (_timer != null)
            {
                _timer.Dispose();
                _timer = null;
            }
        }

        /// <summary>
        /// Timer callback that drives the streaming of buffered activities to the client.
        /// </summary>
        /// <remarks>
        /// This method is invoked on each timer tick while a stream is active. On every pass it:
        /// <list type="number">
        /// <item><description>Guards against re-entrancy: if a previous callback is still running (<see cref="_processingTimer"/>), it returns immediately.</description></item>
        /// <item><description>Updates <see cref="_streamElapsedTime"/> based on the time since the stream started.</description></item>
        /// <item><description>For the M365 Copilot (BizChat) channel, evaluates two conditions:
        ///     <list type="bullet">
        ///     <item><description><b>Timeout:</b> if the total elapsed time is at or beyond <see cref="M365StreamingTimeout"/>, the stream is considered timed out. Depending on whether any text has been sent, either a timeout message or a space plus terminating block is sent, the timer is stopped, and streaming is disabled so the channel falls back to async (non-streaming) delivery.</description></item>
        ///     <item><description><b>Working notice:</b> if more than <see cref="BizChatWorkingNoticeInterval"/> (~45 seconds) has elapsed since the last pass and the queue is empty, an informative "working" update is queued to keep the BizChat stream alive.</description></item>
        ///     </list>
        /// </description></item>
        /// <item><description>Dequeues and sends the next buffered activity (if any). If the queue is empty and the stream has ended, it signals completion and stops the timer; otherwise it shortens the interval to pick up the next chunk sooner.</description></item>
        /// </list>
        /// Because the timer runs on a background thread, exceptions are handled within <see cref="SendActivityAsync"/> rather than propagated, and awaits are performed outside of any <c>lock</c>.
        /// </remarks>
        /// <param name="state">State object supplied by the <see cref="Timer"/> callback. Not used.</param>
        private async void SendIntermediateMessage(object state)
        {
            if (_processingTimer)
            {
                // Skip if the previous timer callback is still running.  This can happen if the callback takes longer than the interval.
                return;
            }
            try
            {
                lock (this)
                {
                    // Set working to prevent stepping on ourselves. 
                    _processingTimer = true;
                }

                IActivity activity = null;

                // update run elapsed time
                _streamElapsedTime = DateTime.UtcNow - _streamStartTime.Value;

                bool bizChatTimeout = false;
                bool sendBizChatWorkingNotice = false;
                // This check is here as if we landed here, the streaming has started, and active and we are trying to push events. 
                if (_channelId == Channels.M365Copilot)
                {
                    // 1. If the overall elapsed time equals or exceeds the M365 streaming timeout, flag that BizChat has timed out.
                    if (_streamElapsedTime >= M365StreamingTimeout)
                    {
                        bizChatTimeout = true;
                        System.Diagnostics.Debug.WriteLine($"BizChat Stream Timeout triggered at {_streamElapsedTime.ToString()}");
                    }

                    // 2. If it has been more than 45 seconds since the last pass, and nothing has been queued and no
                    //    informational message has been sent, flag that we need to send a 'working' notice to BizChat.
                    //    this needs to be reset after each time we send a working notice, so we don't keep sending them.
                    TimeSpan timeSinceLastPass = DateTime.UtcNow - (_lastPassTime ?? _streamStartTime.Value);
                    if (timeSinceLastPass > BizChatWorkingNoticeInterval
                        && _queue.Count == 0)
                    {
                        sendBizChatWorkingNotice = true;
                        System.Diagnostics.Debug.WriteLine($"BizChat No Activity Alert triggered at {_streamElapsedTime.ToString()}");
                    }
                }

                if (bizChatTimeout)
                {
                    // BizChat has exceeded the M365 streaming timeout.  In this case we must check to see if we have sent any text so far and if not send a timeout message. 
                    // if we have sent text we will send a space + block to indicate that the stream is ending and then move on. 
                    // We will exit from here as any queue buffer would be lost if we try to send it, we it will turn into final message. 

                    _streamTimedOut = false; // We do not want to set this flag as this signals the system to use update Async to send the final message.  We want to send a new message to the user that the stream has timed out.
                    List<IActivity> timedOutActivitiesForBizChat = new List<IActivity>();

                    if (string.IsNullOrEmpty(Message))
                    {
                        System.Diagnostics.Debug.WriteLine($"BizChat Stream Timeout triggered at {_streamElapsedTime.ToString()} and no text has been sent, sending timeout message.");
                        timedOutActivitiesForBizChat.Add(CreateStreamTimedOutMessage(true));
                    }
                    else
                    {
                        System.Diagnostics.Debug.WriteLine($"BizChat Stream Timeout triggered at {_streamElapsedTime.ToString()} with text sent, sending space + block to indicate stream is ending.");

                        timedOutActivitiesForBizChat.AddRange(
                            [
                                CreateStreamTimedOutMessage(),
                                CreateStreamTimedOutMessage(true)
                            ]
                        );
                    }

                    foreach (var activityToSend in timedOutActivitiesForBizChat)
                    {
                        await SendActivityAsync(activityToSend, CancellationToken.None).ConfigureAwait(false);
                    }
                    
                    lock (this)
                    {
                        StopStream();
                        _canceled = false;
                        _queueEmpty.Set();
                    }

                    IsStreamingChannel = false; // Disabled Streaming for this channel / Switch to Async Mode.
                    return;
                }

                if (sendBizChatWorkingNotice)
                {
                    // Send a 'working' informational notice to BizChat to keep the stream alive.
                    string informationalToSend = string.IsNullOrWhiteSpace(_lastInformationalMessageSent) ? StreamingTakingTooLongMessage : _lastInformationalMessageSent;
                    System.Diagnostics.Debug.WriteLine($"BizChat No Activity Alert triggered at {_streamElapsedTime.ToString()} sending informational message: {informationalToSend}");

                    await QueueInformativeUpdateAsync(informationalToSend).ConfigureAwait(false);
                    sendBizChatWorkingNotice = false;
                }

                lock (this)
                {
                    QueueNextChunkActivity();

                    if (_queue.Count > 0)
                    {
                        activity = _queue[0]();
                        _queue.RemoveAt(0);

                        // Limit to one interval at a time. They can overlap if the SendActivityAsync takes
                        // longer than the Interval. MSAL can take longer than the interval in some cases,
                        // which case out of sequence messages.
                        _timer.Change(Timeout.Infinite, Timeout.Infinite);
                    }
                    else if (_ended)
                    {
                        _queueEmpty.Set();
                        StopStream();
                        return;
                    }
                    else
                    {
                        // Nothing is in the queue, and not ending, so chances are
                        // the chunking is slow.  We can speed up the interval to
                        // pick up the next chunk faster.
                        _timer.Change(200, Timeout.Infinite);
                        return;
                    }
                }

                // Looks a bit odd, but can't call await inside a lock.
                await SendActivityAsync(activity, CancellationToken.None).ConfigureAwait(false);
            }
            finally
            {
                lock (this)
                {
                    _processingTimer = false;
                }
            }
        }

        private async Task SendActivityAsync(IActivity activity, CancellationToken cancellationToken)
        {
            if (activity != null)
            {
                if (_streamStartTime == null)
                {
                    // start timestamp for the first activity sent, which is used to determine if the stream has timed out -  This is needed as some clients have activity timeouts that need to be handled by the bot.
                    // For example, Teams has a 2 minute timeout for activities sent to the client, once exceeded, the streaming system must switch to update the activity with the final message instead of sending intermediate messages.
                    // BizChat requires and update ~45 seconds after the first activity is sent to the client, otherwise it will timeout and the user will see a "Something went wrong" message.
                    _streamStartTime = DateTime.UtcNow;
                }

                if (!string.IsNullOrEmpty(StreamId))
                {
                    activity.Id = StreamId;
                    activity.GetStreamingEntity().StreamId = StreamId;
                }

                try
                {
                    var response = await _context.SendActivityAsync(activity, cancellationToken).ConfigureAwait(false);
                    if (string.IsNullOrEmpty(StreamId))
                    {
                        StreamId = response.Id;
                    }

                    // Restart the timer with normal Interval (if running)
                    _timer?.Change(Interval, Timeout.Infinite);
                }
                catch (Exception ex)
                {
                    // We are not rethrowing from here since this is likely being called
                    // from the Timer thread and will crash the app.  A more elegant 
                    // solution would be to get it back to the calling thread.

                    bool CanceledStream = true; // logging flag and general cancellation handler
                    if (ex is ErrorResponseException errorResponse)
                    {
                        // User canceled?
                        if (TeamsStreamCancelled.Equals(errorResponse?.Body?.Error?.Code, StringComparison.OrdinalIgnoreCase))
                        {
                            if (errorResponse?.Body?.Error?.Message != null &&
                                errorResponse.Body.Error.Message.Equals(TeamsStreamTimedOut, StringComparison.OrdinalIgnoreCase))
                            {
                                // stream timeout 
                                _context?.Adapter?.Logger?.LogWarning("Client canceled due to exceeded allowed streaming time. {errorResponse?.Body?.Error?.Code} - {errorResponse?.Body?.Error?.Message}", errorResponse?.Body?.Error?.Code, errorResponse?.Body?.Error?.Message);
                                System.Diagnostics.Trace.WriteLine($"Client canceled due to exceeded allowed streaming time. {errorResponse?.Body?.Error?.Code} - {errorResponse?.Body?.Error?.Message}");

                                _streamTimedOut = true;
                                IsStreamingChannel = false; // Disabled Streaming for this channel / Switch to Async Mode.
                                CanceledStream = false;

                                // Send a message to the user that the stream timed out.
                                await SendStreamTimeOutCheckpoint(cancellationToken);
                            }
                            else
                            {

                                _context?.Adapter?.Logger?.LogWarning("User canceled stream on the client side. {errorResponse?.Body?.Error?.Code} - {errorResponse?.Body?.Error?.Message}", errorResponse?.Body?.Error?.Code, errorResponse?.Body?.Error?.Message);
                                System.Diagnostics.Trace.WriteLine($"User canceled stream on the client side. {errorResponse?.Body?.Error?.Code} - {errorResponse?.Body?.Error?.Message}");
                                _userCanceled = true;
                            }
                        }
                        // Stream not allowed?
#pragma warning disable CA1862 // Use the 'StringComparison' method overloads to perform case-insensitive string comparisons - this is to support older .NET versions
                        else if (BadArgument.Equals(errorResponse?.Body?.Error?.Code, StringComparison.OrdinalIgnoreCase) &&
                            errorResponse?.Body?.Error?.Message.ToLower().Contains(TeamsStreamNotAllowed) == true)
                        {
                            _context?.Adapter?.Logger?.LogWarning("Interaction Context does not support StreamingResponse, StreamingResponse has been disabled for this turn");
                            System.Diagnostics.Trace.WriteLine("Interaction Context does not support StreamingResponse, StreamingResponse has been disabled for this turn");

                            IsStreamingChannel = false; // Disabled Streaming for this channel / interaction as teams will not accept it at this time. 
                            CanceledStream = false;
                        }
#pragma warning restore CA1862 // Use the 'StringComparison' method overloads to perform case-insensitive string comparisons
                        else
                        {
                            var errorMessage = errorResponse?.Body?.Error?.Message ?? "None";

                            _context?.Adapter?.Logger?.LogWarning(
                                "Exception during StreamingResponse: {ExceptionMessage} - {ErrorMessage}",
                                ex.Message,
                                errorMessage);

                            System.Diagnostics.Trace.WriteLine($"Exception during StreamingResponse: {ex.Message} - {errorMessage}");
                        }

                        if (CanceledStream)
                        {
                            _context?.Adapter?.Logger?.LogWarning("User canceled stream on the client side.");
                            System.Diagnostics.Trace.WriteLine("User canceled stream on the client side.");
                        }
                    }

                    lock (this)
                    {
                        StopStream();
                        _canceled = CanceledStream;
                        _queueEmpty.Set();
                    }
                }
            }
        }

        /// <summary>
        /// Updates an existing activity on the client, typically used to replace an in-progress
        /// streaming message with the final (or a timed-out) message.
        /// </summary>
        /// <remarks>
        /// If <paramref name="activity"/> is <c>null</c>, no update is performed and <c>null</c> is returned.
        /// Any exception thrown while updating is caught and logged (with additional detail extracted for
        /// <see cref="ErrorResponseException"/>) rather than propagated, so a failed update does not crash the
        /// caller — commonly invoked from the streaming/timer path. On failure, <c>null</c> is returned.
        /// </remarks>
        /// <param name="activity">The activity to send as an update. If <c>null</c>, the call is a no-op.</param>
        /// <param name="cancellationToken">A token used to cancel the update operation.</param>
        /// <returns>
        /// The <see cref="ResourceResponse"/> returned by the underlying update, or <c>null</c> if
        /// <paramref name="activity"/> was <c>null</c> or the update failed.
        /// </returns>
        private async Task<ResourceResponse> UpdateActivityAsync(IActivity activity, CancellationToken cancellationToken = default)
        {
            if (activity != null)
            {
                try
                {
                    var response = await _context.UpdateActivityAsync(activity, cancellationToken).ConfigureAwait(false);
                    return response;
                }
                catch (Exception ex)
                {
                    if ( ex is ErrorResponseException errorResponse)
                    {
                        var errorMessage = errorResponse?.Body?.Error?.Message ?? "None";
                        _context?.Adapter?.Logger?.LogWarning(
                            "Exception during StreamingResponse UpdateActivity: {ExceptionMessage} - {ErrorMessage}",
                            ex.Message,
                            errorMessage);
                        System.Diagnostics.Trace.WriteLine($"Exception during StreamingResponse UpdateActivity: {ex.Message} - {errorMessage}");
                    }
                    else
                    {
                        _context?.Adapter?.Logger?.LogWarning(
                            "Exception during StreamingResponse UpdateActivity: {ExceptionMessage}",
                            ex.Message);
                        System.Diagnostics.Trace.WriteLine($"Exception during StreamingResponse UpdateActivity: {ex.Message}");
                    }

                }
            }
            return null;

        }
    }
}
