//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Agents.Connector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Agents.Connector.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Access Token created to respond to a request from the agent was rejected by the remote endpoint.  This can be caused by the incorrect connection configuration. Please verify that configuration against the expected configuration. .
        /// </summary>
        internal static string ConversationResponseUnAuthorized {
            get {
                return ResourceManager.GetString("ConversationResponseUnAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateConversation operation returned an invalid status code &apos;({0}) {1}&apos;.
        /// </summary>
        internal static string CreateConversationError {
            get {
                return ResourceManager.GetString("CreateConversationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAttachment operation returned an invalid status code &apos;({0}) {1}&apos;.
        /// </summary>
        internal static string GetAttachment_Error {
            get {
                return ResourceManager.GetString("GetAttachment_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAttachmentInfo operation returned an invalid status code &apos;({0}) {1}&apos;.
        /// </summary>
        internal static string GetAttachmentInfoError {
            get {
                return ResourceManager.GetString("GetAttachmentInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetConversations operation returned an invalid status code &apos;({0}) {1}&apos;.
        /// </summary>
        internal static string GetConversationsError {
            get {
                return ResourceManager.GetString("GetConversationsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate the OAuth Configuration.  If you are using Azure Bot Service, please verify that the OAuth configuration exists.
        /// </summary>
        internal static string GetSignInResourceAsync_BadRequest {
            get {
                return ResourceManager.GetString("GetSignInResourceAsync_BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReplyToActivity operation returned an invalid status code &apos;({0}) {1}&apos;.
        /// </summary>
        internal static string ReplyToActivityError {
            get {
                return ResourceManager.GetString("ReplyToActivityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SendConversationHistory operation returned an invalid status code &apos;({0}) {1}&apos;.
        /// </summary>
        internal static string SendConversationHistoryError {
            get {
                return ResourceManager.GetString("SendConversationHistoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteActivity operation returned an invalid status code &apos;({0}) {1}&apos;.
        /// </summary>
        internal static string SendDeleteActivity {
            get {
                return ResourceManager.GetString("SendDeleteActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteConversationMember operation returned an invalid status code &apos;({0}) {1}&apos;.
        /// </summary>
        internal static string SendDeleteConversationMember {
            get {
                return ResourceManager.GetString("SendDeleteConversationMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetActivityMembers operation returned an invalid status code &apos;({0}) {1}&apos;.
        /// </summary>
        internal static string SendGetActivityMembers {
            get {
                return ResourceManager.GetString("SendGetActivityMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetConversationMember operation returned an invalid status code &apos;({0}) {1}&apos;.
        /// </summary>
        internal static string SendGetConversationMember {
            get {
                return ResourceManager.GetString("SendGetConversationMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetConversationMembers operation returned an invalid status code &apos;({0}) {1}&apos;.
        /// </summary>
        internal static string SendGetConversationMembers {
            get {
                return ResourceManager.GetString("SendGetConversationMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetConversationPagedMembers operation returned an invalid status code &apos;({0}) {1}&apos;.
        /// </summary>
        internal static string SendGetConversationPagedMembers {
            get {
                return ResourceManager.GetString("SendGetConversationPagedMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SendToConversation operation returned an invalid status code &apos;({0}) {1}&apos;.
        /// </summary>
        internal static string SendToConversationError {
            get {
                return ResourceManager.GetString("SendToConversationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateActivity operation returned an invalid status code &apos;({0}) {1}&apos;.
        /// </summary>
        internal static string SendUpdateActivityError {
            get {
                return ResourceManager.GetString("SendUpdateActivityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UploadAttachment operation returned an invalid status code &apos;({0}) {1}&apos;.
        /// </summary>
        internal static string SendUploadAttachment {
            get {
                return ResourceManager.GetString("SendUploadAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Token Service was unable to exchange the token.  Check OAuth Connection configuration for &apos;{0}&apos; on the Azure Bot and try again.  The response is &apos;{1}&apos;.
        /// </summary>
        internal static string TokenServiceExchangeErrorResponse {
            get {
                return ResourceManager.GetString("TokenServiceExchangeErrorResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Token Service was unable to exchange the token.  Check OAuth Connection configuration for &apos;{0}&apos; on the Azure Bot and try again..
        /// </summary>
        internal static string TokenServiceExchangeFailed {
            get {
                return ResourceManager.GetString("TokenServiceExchangeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Token Service returned an unexpected response for Exchange: &apos;({0}) {1}&apos;.
        /// </summary>
        internal static string TokenServiceExchangeUnexpected {
            get {
                return ResourceManager.GetString("TokenServiceExchangeUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Token Service returned an unexpected response for GetAadToken: &apos;({0}) {1}&apos;.
        /// </summary>
        internal static string TokenServiceGetAadTokenUnexpected {
            get {
                return ResourceManager.GetString("TokenServiceGetAadTokenUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Token Service returned an unexpected response for GetSignInResource: &apos;({0}) {1}&apos;.
        /// </summary>
        internal static string TokenServiceGetSignInResourceUnexpected {
            get {
                return ResourceManager.GetString("TokenServiceGetSignInResourceUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Token Service returned an unexpected response for GetSignInUrl: &apos;({0}) {1}&apos;.
        /// </summary>
        internal static string TokenServiceGetSignInUrlUnexpected {
            get {
                return ResourceManager.GetString("TokenServiceGetSignInUrlUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Token Service returned an unexpected response for GetTokenOrSignInResource: &apos;({0}) {1}&apos;.
        /// </summary>
        internal static string TokenServiceGetTokenOrSignInResourceUnexpected {
            get {
                return ResourceManager.GetString("TokenServiceGetTokenOrSignInResourceUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Token Service returned an unexpected response for GetTokenStatus: &apos;({0}) {1}&apos;.
        /// </summary>
        internal static string TokenServiceGetTokenStatusUnexpected {
            get {
                return ResourceManager.GetString("TokenServiceGetTokenStatusUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Token Service returned an unexpected response for GetToken: &apos;({0}) {1}&apos;.
        /// </summary>
        internal static string TokenServiceGetTokenUnexpected {
            get {
                return ResourceManager.GetString("TokenServiceGetTokenUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Token Service returned an unexpected response for SignOut: &apos;({0}) {1}&apos;.
        /// </summary>
        internal static string TokenServiceSignOutUnexpected {
            get {
                return ResourceManager.GetString("TokenServiceSignOutUnexpected", resourceCulture);
            }
        }
    }
}
