name: Get Azure DevOps Access Token
description: Get an access token to authenticate with Azure DevOps
inputs:
  client-id:
    description: "The client ID of the application calling Azure DevOps"
    required: true
  tenant-id:
    description: "The tenant ID of the application calling Azure DevOps"
    required: true
  organization:
    description: "The Azure DevOps organization to authenticate with"
    required: true
outputs:
  token:
    description: "The access token to authenticate with Azure DevOps"
    value: ${{ steps.ADOAuth.outputs.token }}

runs:
  using: "composite"
  steps:
    - name: OIDC Login with AzPowershell
      uses: azure/login@7184910d9eb2b1c5e48f7073824a90609bb9b6d6 # v2.3.1
      with:
        client-id: ${{ inputs.client-id }}
        tenant-id: ${{ inputs.tenant-id }}
        allow-no-subscriptions: true
        enable-AzPSSession: true
    - id: ADOAuth
      name: Get ADO Access Token
      uses: azure/powershell@1300bbd2b3e1c21c029fe34887d16d2809a1397f # v1.4.0
      with:
        azPSVersion: "latest"
        inlineScript: |
          function decodeToken([string]$token) { 
            $t = $token.split('.')[1]
            while($t.Length % 4 -ne 0) { $t += '=' } 
            ConvertFrom-Json ([System.Text.Encoding]::Ascii.GetString([System.Convert]::FromBase64String($t)))
          }

          $accessToken = az account get-access-token --resource="https://${{inputs.organization}}.visualstudio.com" --query accessToken
          decodeToken($accessToken)
          "token=$accessToken" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
