<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IncludeAspNetSampleHelpers>false</IncludeAspNetSampleHelpers>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="wwwroot\**" />
		<Content Remove="wwwroot\**" />
		<EmbeddedResource Remove="wwwroot\**" />
		<None Remove="wwwroot\**" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\libraries\Hosting\AspNetCore\Microsoft.Agents.Hosting.AspNetCore.csproj" />
		<ProjectReference Include="..\..\libraries\Hosting\DirectLine.NamedPipes\Microsoft.Agents.Hosting.DirectLine.NamedPipes.csproj" />
	</ItemGroup>

</Project>
