//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Agents.Hosting.AspNetCore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Agents.Hosting.AspNetCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A duplicate ContinueConversationAttribute was specified: &apos;{0}&apos;.
        /// </summary>
        internal static string HttpProactiveDuplicateContinueKey {
            get {
                return ResourceManager.GetString("HttpProactiveDuplicateContinueKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SendActivity is missing the &apos;Activity&apos; JSON body.
        /// </summary>
        internal static string HttpProactiveMissingActivityBody {
            get {
                return ResourceManager.GetString("HttpProactiveMissingActivityBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue conversation is missing the &apos;Conversation&apos; JSON body.
        /// </summary>
        internal static string HttpProactiveMissingConversationBody {
            get {
                return ResourceManager.GetString("HttpProactiveMissingConversationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create conversation is missing the &apos;CreateConversationBody&apos; JSON body.
        /// </summary>
        internal static string HttpProactiveMissingCreateBody {
            get {
                return ResourceManager.GetString("HttpProactiveMissingCreateBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SendActivity is missing the &apos;SendToConversationBody&apos; JSON body.
        /// </summary>
        internal static string HttpProactiveMissingSendBody {
            get {
                return ResourceManager.GetString("HttpProactiveMissingSendBody", resourceCulture);
            }
        }
    }
}
