// -----------------------------------------------------------------------------
//  Copyright (c) Microsoft Corporation.  All rights reserved.
// -----------------------------------------------------------------------------

using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Xunit;

namespace Microsoft.Agents.Core.Analyzers.Tests;

[Trait("Category", "Manual")]
public class PreloadAssembliesSourceGeneratorTests
{
    [Fact]
    public async Task Validate_TypeRegistryAsync()
    {
        const string source = /* lang=c#-test */ """
            namespace TestNamespace;
            public class TestClass
            {
            }
            """;

        const string directReferenceSource = /* lang=c#-test */ """
            namespace TestNamespace.Direct;
            public class DerivedType : Microsoft.Agents.Core.Models.Entity
            {
            }
            """;

        const string transientReferenceSource = /* lang=c#-test */ """
            namespace TestNamespace.Transitive;
            public class DerivedType : Microsoft.Agents.Core.Models.Entity
            {
            }
            """;

        const string generated = /* lang=c#-test */ """
            // <auto-generated />
            using System;
            using System.Runtime.CompilerServices;
            
            internal static class PreloadTypesRegistry
            {
                private static readonly Type[] s_preloadedTypes;
                static PreloadTypesRegistry()
                {
                    s_preloadedTypes = new[]
                    {
                        typeof(global::TestNamespace.Direct.DerivedType)
                    };
                }
            
                [ModuleInitializer]
                internal static void Initialize()
                {
                    _ = s_preloadedTypes.Length;
                }
            }
            """;

        var generator = GetSourceGeneratorTest(source, directReferenceSource, transientReferenceSource, generated);

        await generator.RunAsync(TestContext.Current.CancellationToken);
    }

    private static SourceGeneratorTest<DefaultVerifier> GetSourceGeneratorTest(string source, string directReferenceSource, string transientReferenceSource, string generated) => new CSharpSourceGeneratorTest<PreloadAssembliesSourceGenerator, DefaultVerifier>
    {
        TestState =
            {
                Sources = { source },
                AdditionalProjects =
                {
                    ["MainDependencyProject"] =
                    {
                        Sources =
                        {
                            /* lang=c#-test */ """
                            namespace Microsoft.Agents.Core.Models;
                            public abstract class Entity
                            {
                            }

                            public class SubEntity : Entity
                            {
                            }
                            """
                        }
                    },
                    ["DirectDependency"] =
                    {
                        Sources =
                        {
                            directReferenceSource
                        },
                        AdditionalProjectReferences =
                        {
                            "MainDependencyProject", "TransientDependency"
                        },
                    },
                    ["TransientDependency"] =
                    {
                        Sources =
                        {
                            transientReferenceSource
                        },
                        AdditionalProjectReferences =
                        {
                            "MainDependencyProject"
                        },
                    },
                },
                AdditionalProjectReferences =
                {
                    "DirectDependency",
                    "MainDependencyProject",
                },
                GeneratedSources =
                {
                    (typeof(PreloadAssembliesSourceGenerator), "PreloadedAssemblies.g.cs", generated),
                },
            },
        ReferenceAssemblies = ReferenceAssemblies.Net.Net80.AddPackages(new PackageIdentity[]
            {
            }.ToImmutableArray())
    };
}