// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Microsoft.Agents.Hosting.A2A.Protocol;

/// <summary>
/// Carries a new or updated artifact (or a chunk of an artifact) generated by the task 
/// during streaming. This is one of the possible result types in a SendTaskStreamingResponse.
/// </summary>
public sealed class TaskArtifactUpdateEvent
{
    [JsonPropertyName("kind")]
    public string Kind { get; } = "artifact-update";

    /// <summary>
    /// Task ID being updated
    /// </summary>
    [JsonPropertyName("taskId")]
    public required string TaskId { get; set; }

    /// <summary>
    /// Context ID the task is associated with
    /// </summary>
    [JsonPropertyName("contextId")]
    public required string ContextId { get; set; }

    /// <summary>
    /// The Artifact data. Could be a complete artifact or an incremental chunk.
    /// </summary>
    [JsonPropertyName("artifact")]
    public required Artifact Artifact { get; set; }

    /// <summary>
    /// true means append parts to artifact; false (default) means replace.
    /// </summary>
    [JsonPropertyName("append")]
    public bool? Append { get; set; }

    /// <summary>
    /// true indicates this is the final update for the artifact.
    /// </summary>
    [JsonPropertyName("lastChunk")]
    public bool? LastChunk { get; set; }

    /// <summary>
    /// Event-specific metadata.
    /// </summary>
    [JsonPropertyName("metadata")]
    public IReadOnlyDictionary<string, object>? Metadata { get; set; }
}