name: Local build and test

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "rel/**" ]

jobs:
  build:
    runs-on: windows-latest
    steps:

    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
      with:
        dotnet-version: 10.0.x

    - uses: dotnet/nbgv@705dad19ab067f12f4e9eeaa60812e01edef5d25 # v0.5.2
      with:
          setAllVars: true        
    - run: echo "NuGetPackageVersion $NuGetPackageVersion"      

    - name: Restore
      run: dotnet restore AgentSdk.proj
  
    - name: Build
      run: dotnet build --no-restore -c debug AgentSdk.proj

    - name: Package
      run: dotnet pack --no-build --no-restore -c debug src/Microsoft.Agents.SDK.sln 

    - name: Test in net8
      run: dotnet test --no-build --no-restore -c debug ./src/ -f net8.0

    - name: Test in net10
      run: dotnet test --no-build --no-restore -c debug ./src/ -f net10.0